as2/as2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('quotaapp/', include('quotaapp.urls'))
]

as2/quotaapp/urls.py
from django.urls import path, include
from . import views

app_name = "quotaapp"

urlpatterns = [
    path('', views.index, name='index'),
    path('quota_request/', views.quota_request, name='quota_request'),
    path('quota_semester2/', views.quota_semester2, name='quota_semester2'),
    path('cancel/<str:course>', views.cancel, name='cancel'),
    path('request/<str:course>', views.request, name='request'),
    path('complete/', views.complete, name='complete'),
]

as2/users/urls.py
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [

    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('quotaapp/', include('quotaapp.urls'))

]

as2/quotaapp/models.py
from email.policy import default
from enum import unique
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Subject(models.Model):
    subject_id = models.CharField(max_length=64, primary_key=True)
    subject_name = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.subject_id} {self.subject_name}"


class Course(models.Model):
    course = models.ForeignKey(Subject, on_delete=models.CASCADE)
    semester = models.CharField(max_length=64)
    year = models.CharField(max_length=64)
    seat = models.PositiveIntegerField(default=0)
    current_seat = models.PositiveIntegerField(default=0)
    q_status = models.CharField(max_length=64, choices=[(
        'Available', 'Available'), ('Full', 'Full')], default="Available")
    status = models.BooleanField(default=True)

    class Meta:
        unique_together = ['course', 'semester', 'year']

    def __str__(self):
        return f"{self.course.subject_id} {self.semester} {self.year}"

    def is_seat_available(self):
        return self.student_apply.count() < self.seat


class Student(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    applys = models.ManyToManyField(
        Course, blank=True, related_name="student_apply")

    def __str__(self):
        return f"{self.student} {self.student.first_name} {self.student.last_name}"

as2/users/models.py
from django.db import models

# Create your models here.

as2/quotaapp/views.py
from django.shortcuts import render
from .models import Course, Student, Subject
from django.contrib.auth.models import User
# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        subjects = Course.objects.filter(status=True)
        return render(request, 'quotaapp/index.html', {
            'subjects': subjects
        })


def quota_request(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()
        other_course = Course.objects.exclude(
            id__in=course_apply.values_list('id', flat=True)).filter(status=True)

        return render(request, 'quotaapp/quota_request.html', {
            'student_info': student_info,
            'course_apply': course_apply,
            'other_course': other_course,
        })


def quota_semester2(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()
        other_course = Course.objects.exclude(
            id__in=course_apply.values_list('id', flat=True)).filter(status=True)

        return render(request, 'quotaapp/quota_semester2.html', {
            'student_info': student_info,
            'course_apply': course_apply,
            'other_course': other_course,
        })


def complete(request):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        course_apply = student_info.applys.all()

        return render(request, 'quotaapp/complete.html', {
            'student_info': student_info,
            'course_apply': course_apply,
        })


def cancel(request, course):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        course = course.split(' ')
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        subject_course = Subject.objects.get(subject_id=course[0])
        cancel_course = Course.objects.filter(
            course=subject_course, semester=course[1], year=course[2]).first()

        student_info.applys.remove(cancel_course)
        cancel_course.current_seat = cancel_course.student_apply.count()
        if cancel_course.is_seat_available():
            cancel_course.q_status = 'Available'
        cancel_course.save()

        if cancel_course.semester == '1':
            return quota_request(request)
        else:
            return quota_semester2(request)


def request(request, course):
    if not request.user.is_authenticated:
        return render(request, 'users/login.html')
    else:
        course = course.split(' ')
        student = User.objects.get(username=request.user)
        student_info = Student.objects.get(student=student)
        subject_course = Subject.objects.get(subject_id=course[0])
        request_course = Course.objects.filter(
            course=subject_course, semester=course[1], year=course[2]).first()

        if request_course.is_seat_available():
            student_info.applys.add(request_course)
            request_course.current_seat = request_course.student_apply.count()
            if not request_course.is_seat_available():
                request_course.q_status = 'Full'
            request_course.save()

        if request_course.semester == '1':
            return quota_request(request)
        else:
            return quota_semester2(request)

as2/users/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse('users:login'))
    else:
        return render(request, 'users/index.html')


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            # return HttpResponseRedirect(reverse('users:index'))
            if not user.is_superuser:
                return HttpResponseRedirect(reverse('users:index'))
            else:
                return redirect('/admin/')
        else:
            return render(request, 'users/login.html', {
                'message': 'Invalid credentials.'
            })
    return render(request, 'users/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'users/login.html', {
        'message': 'Logged out'
    })

as2/quotaapp/templates/quotaapp/complete.html
{% extends 'quotaapp/layout.html' %}
{% block body %}

<h1 style="color:rgb(19, 125, 139);">ผลการขอโควต้า</u></h1>

<table id="customers">
    <tr>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ภาคเรียนที่ </center>
        </th>
        <th style="font-size:125%;">
            <center> ปีการศึกษา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
    </tr>
    {%for apply in course_apply %}
    <tr>
        <td>{{apply.course.subject_id}}</td>
        <td>{{apply.course.subject_name}}</td>
        <td>{{apply.semester}}</td>
        <td>{{apply.year}}</td>
        <td>{{apply.current_seat}} / {{apply.seat}}</td>
    </tr>
    {% endfor %}
</table>
<h2></h2>
<center>
    <a href="{% url 'users:index' %}">กลับหน้าหลัก</a>
</center>
{% endblock %}

as2/quotaapp/templates/quotaapp/index.html
{% extends 'quotaapp/layout.html' %}
{% block body %}

<h1 style="color:rgb(19, 121, 139);">รายวิชา</u></h1>

<h2 style="color:rgb(19, 125, 139);">ภาคการศึกษาที่ 1</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    <ul>
        {% for subject in subjects %}
        <tr>
            {% if subject.semester == '1' %}
            <td>{{ subject.course.subject_id }}</td>
            <td>{{ subject.course.subject_name }}</td>
            <td>{{ subject.current_seat }} / {{ subject.seat }}</td>
            <td style="color:rgb(47, 0, 255);">{{ subject.q_status }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </ul>
</table>

<h2 style="color:rgb(19, 125, 139);">ภาคการศึกษาที่ 2</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    <ul>
        {% for subject in subjects %}
        <tr>
            {% if subject.semester == '2' %}
            <td>{{ subject.course.subject_id }}</td>
            <td>{{ subject.course.subject_name }}</td>
            <td>{{ subject.current_seat }} / {{ subject.seat }}</td>
            <td style="color:rgb(47, 0, 255);">{{ subject.q_status }}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </ul>
</table>

<h1></h1>

<center>
    <a href="{% url 'users:index' %}">กลับหน้าหลัก</a>
    {% endblock %}

as2/quotaapp/templates/quotaapp/layout.html
<!DOCTYPE html>
<html lang='en'>

<head>
    <title>subjects</title>
    <style>
        h1 {
            text-align: center;
        }

        a:link,
        a:visited {
            background-color: rgb(96, 155, 244);
            color: white;
            padding: 15px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover,
        a:active {
            background-color: rgb(255, 94, 0);
        }

        table,
        td,
        th,
        tr {
            border: 1px solid #ffffff;
            text-align: center;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            padding: 15px;
        }

        .right {
            float: right;
        }

        #customers td,
        #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even) {
            background-color: rgb(215, 246, 250);
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #8ca8d2;
            color: white
        }
    </style>
</head>

<body style="background-color:rgb(215, 246, 250)">
    {% block body %}
    {% endblock %}
</body>

</html>

as2/quotaapp/templates/quotaapp/quota_request.html
{% extends 'quotaapp/layout.html' %}
{% block body %}

<h1 style="color:rgb(19, 125, 139);">ขอโควต้าภาคเรียนที่ 1</u></h1>

<h2 style="color:rgb(19, 121, 139);">วิชาที่ขอโควต้า</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;"> </th>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ภาคเรียนที่ </center>
        </th>
        <th style="font-size:125%;">
            <center> ปีการศึกษา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    {%for course in course_apply %}
    <tr>
        <td> <a href="{% url 'quotaapp:cancel' course%}">ยกเลิก</a></td>
        <td>{{course.course.subject_id}}</td>
        <td>{{course.course.subject_name}}</td>
        <td>{{course.semester}}</td>
        <td>{{course.year}}</td>
        <td>{{course.current_seat}} / {{course.seat}}</td>
        <td style="color:rgb(47, 0, 255);">{{course.q_status}}</td>
    </tr>
    {% endfor %}
</table>
<h1></h1>

<h1></h1>
<h2 style="color:rgb(19, 121, 139);">รายวิชาที่เปิดให้ขอโควต้า</u></h2>
<table id="customers">
    <tr>
        <th style="font-size:125%;"> </th>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ภาคเรียนที่ </center>
        </th>
        <th style="font-size:125%;">
            <center> ปีการศึกษา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    {%for course in other_course %}
    <tr>
        {% if course.semester == '1' %}
        <td> <a href="{% url 'quotaapp:request' course%}">เลือก</a></td>
        <td>{{course.course.subject_id}}</td>
        <td>{{course.course.subject_name}}</td>
        <td>{{course.semester}}</td>
        <td>{{course.year}}</td>
        <td>{{course.current_seat}} / {{course.seat}}</td>
        <td style="color:rgb(47, 0, 255);">{{course.q_status}}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
<h1></h1>

<center>
    <a href="{% url 'quotaapp:complete' %}"> ยืนยัน </a>
</center>


<a href="{% url 'users:index' %}">กลับหน้าหลัก</a>


{% endblock %}

as2/quotaapp/templates/quotaapp/quota_semester2.html
{% extends 'quotaapp/layout.html' %}
{% block body %}

<h1 style="color:rgb(19, 125, 139);">ขอโควต้าภาคเรียนที่ 2</u></h1>

<h2 style="color:rgb(19, 121, 139);">วิชาที่ขอโควต้า</u></h2>

<table id="customers">
    <tr>
        <th style="font-size:125%;"> </th>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ภาคเรียนที่ </center>
        </th>
        <th style="font-size:125%;">
            <center> ปีการศึกษา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    {%for course in course_apply %}
    <tr>
        <td> <a href="{% url 'quotaapp:cancel' course%}">ยกเลิก</a></td>
        <td>{{course.course.subject_id}}</td>
        <td>{{course.course.subject_name}}</td>
        <td>{{course.semester}}</td>
        <td>{{course.year}}</td>
        <td>{{course.current_seat}} / {{course.seat}}</td>
        <td style="color:rgb(47, 0, 255);">{{course.q_status}}</td>
    </tr>
    {% endfor %}
</table>
<h1></h1>

<h1></h1>
<h2 style="color:rgb(19, 121, 139);">รายวิชาที่เปิดให้ขอโควต้า</u></h2>
<table id="customers">
    <tr>
        <th style="font-size:125%;"> </th>
        <th style="font-size:125%;">
            <center> รหัสวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ชื่อวิชา </center>
        </th>
        <th style="font-size:125%;">
            <center> ภาคเรียนที่ </center>
        </th>
        <th style="font-size:125%;">
            <center> ปีการศึกษา </center>
        </th>
        <th style="font-size:125%;">
            <center> จำนวนที่นั่ง </center>
        </th>
        <th style="font-size:125%;">
            <center> สถานะ </center>
        </th>
    </tr>
    {%for course in other_course %}
    <tr>
        {% if course.semester == '2' %}
        <td> <a href="{% url 'quotaapp:request' course%}">เลือก</a></td>
        <td>{{course.course.subject_id}}</td>
        <td>{{course.course.subject_name}}</td>
        <td>{{course.semester}}</td>
        <td>{{course.year}}</td>
        <td>{{course.current_seat}} / {{course.seat}}</td>
        <td style="color:rgb(47, 0, 255);">{{course.q_status}}</td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
<h1></h1>

<center>
    <a href="{% url 'quotaapp:complete' %}"> ยืนยัน </a>
</center>


<a href="{% url 'users:index' %}">กลับหน้าหลัก</a>


{% endblock %}

as2/users/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Users</title>
    <style>
        h1 {
            color: SaddleBrown;
        }

        h2 {
            color: Peru;
        }

        a:link,
        a:visited {
            background-color: #f44336;
            color: white;
            padding: 15px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover,
        a:active {
            background-color: red;
        }

        .spelling-error {
            text-decoration-line: underline;
            text-decoration-style: wavy;
            text-decoration-color: red;
        }

        .button {
            background-color: SandyBrown;
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }
    </style>

</head>

<body style="background-color:AntiqueWhite">
    <center>
        {% block body %}
        {% endblock %}
    </center>
</body>

</html>

as2/users/templates/login.html
{% extends 'users/layout.html' %}
{% block body %}
<h1 style="font-size:300%;"><u class="spelling-error">Login</u></h1>
{% if message %}
<div style="color:red">{{ message }}</div>
{% endif %}
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <h1></h1>
    <center>
        <button class="button">Login</button>
    </center>
</form>
{% endblock %}

as2/users/templates/users/index.html
{% extends 'users/layout.html' %}
{% block body %}
<h1 style="font-size:300%;">Welcome to quotaapp</u></h1>

<h2 style="font-size:150%;">Username: {{ request.user.username }}</h2>

<a href="{% url 'quotaapp:index' %}">ดูรายวิชา</a>
<h2></h2>
<a href="{% url 'quotaapp:quota_request' %}">ขอโควต้าภาคเรียนที่ 1</a>
<h2></h2>
<a href="{% url 'quotaapp:quota_semester2' %}">ขอโควต้าภาคเรียนที่ 2</a>
<h2></h2>
<a href="{% url 'users:logout' %}">ออกจากระบบ</a>
{% endblock %}

as2/users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Users</title>
    <style>
        h1 {
            color: rgb(19, 91, 139);
        }

        h2 {
            color: rgb(63, 188, 205);
        }

        a:link,
        a:visited {
            background-color: rgb(96, 155, 244);
            color: white;
            padding: 15px 25px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
        }

        a:hover,
        a:active {
            background-color: rgb(255, 94, 0);
        }

        .button {
            background-color: rgb(96, 155, 244);
            border: none;
            color: white;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
        }
    </style>

</head>

<body style="background-color:rgb(215, 246, 250)">
    <center>
        {% block body %}
        {% endblock %}
    </center>
</body>

</html>

as2/users/templates/users/login.html
{% extends 'users/layout.html' %}
{% block body %}
<h1 style="font-size:300%;">Login</u></h1>
{% if message %}
<div style="color:rgb(245, 3, 3)">{{ message }}</div>
{% endif %}
<h1></h1>
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Username">
    <input type="password" name="password" placeholder="Password">
    <h1></h1>
    <center>
        <button class="button">Login</button>
    </center>
</form>
{% endblock %}